sudo: required
language: go
go:
  - "1.13"
stages:
  - build
  - deploy
git:
  submodules: true
  quiet: false
deploy:
  provider: releases
  api_key: ${GITHUB_OAUTH_TOKEN}
  file_glob: true
  file: bin/*
  skip_cleanup: true
  on:
    tags: true
before_script:
  - sudo apt-get update -y
  - sudo apt-get install -y make g++
script:
  - make deps
  - GOOS=linux GOARCH=amd64 make build_production
  - GOOS=darwin GOARCH=amd64 make build_production
  - GOOS=windows GOARCH=386 make build_production
  - ls -al ./bin
